version: "2"
services:
  web:
    restart: always
    image: "node:15"
    volumes:
      - "./backend:/app"
    ports: 
      - "3000:3000"
    entrypoint: ["bash","/app/bin/run.sh"]
  db:
    restart: always
    image: mysql
    volumes:
      - "./data.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"