#数据库驱动mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blogs?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhou20000627
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#日志打印
logging:
  level:
    root: info
    com.yrp: debug
  file: log/blog-dev.log
server:
  port: 8080